server:
  url: https://wiediversistmeingarten.org/api/
station: 
  boxId: 4a936912-65db-475d-bcd6-9ee292079830
  environmentTimeDeltaInMinutes: 2 
  weightThreshold: 5 
  calibration_weight: 0
  terminal_weight: 0
